export const GET_CURRENT_CITY_REQUEST = 'GET_CURRENT_CITY_REQUEST'
export const GET_CURRENT_CITY_SUCCESS = 'GET_CURRENT_CITY_SUCCESS'
export const GET_CURRENT_CITY_FAILURE = 'GET_CURRENT_CITY_FAILURE'

export const ON_INPUT = 'ON_INPUT'
export const ADD_CITY = 'ADD_CITY'
export const DELETE_CITY = 'DELETE_CITY'
export const SET_CURRENT_CITY = 'SET_CURRENT_CITY'