export const GET_COORDS_REQUEST = 'GET_COORDS_REQUEST'
export const GET_COORDS_SUCCESS = 'GET_COORDS_SUCCESS'
export const GET_COORDS_FAILURE = 'GET_COORDS_FAILURE'

export const ADD_CITY = 'ADD_CITY'
export const DELETE_CITY = 'DELETE_CITY'
export const SET_CURRENT_CITY = 'SET_CURRENT_CITY'
