export const GET_FORECAST_REQUEST = 'GET_FORECAST_REQUEST'
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS'
export const GET_FORECAST_FAILURE = 'GET_FORECAST_FAILURE'
export const RESET_FORECAST = 'RESET_FORECAST'